# Generated by Django 4.0.4 on 2022-04-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_completed_alter_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
